### PR TITLE
Add Resource Aware ML link and OCaml mutlicore

### PR DESCRIPTION
**Pull request by XVilka**

### CODE REVIEW

**Comment by XVilka** [comment]
Ping?

**Comment by gasche** [comment]
This looks good, but:

- multicore OCaml should be clearly marked as "experimental", what about saying "ongoing experimental project"?
- RaML should be followed by a newline, and also I think it would be better placed in "languages and compilers" or "Formal Software Verification" rather than "Developer tools"

**Comment by gasche** [comment]
(Apologies for not reacting earlier.)

**Comment by rizo** [comment]
@XVilka, sorry for the delay. This is indeed an important addition.

What worries me is that the state of the project is not clear from that link. Maybe we should include a reference to your [development report](https://discuss.ocaml.org/t/ocaml-multicore-report-on-a-june-2018-development-meeting-in-paris/2202), @gasche?

**Comment by XVilka** [comment]
@gasche fixed.

**Comment by gasche** [comment]
@rizo: I wouldn't personally include a link to the report because it's bound to become outdated at some point. Pointing to the project homepage is the best choice I think, they can decide to point to any material (including the report) to describe the current status.

**Comment by gasche** [comment]
(I think the PR is mergeable now.)

**Comment by rizo** [comment]
Merging! Thanks both!

**Pull request merged**
