### PR TITLE
update the cornell course to latest one and add UIUC course

### PR DESCRIPTION
**Pull request by Xuefeng-Zhu**

### CODE REVIEW

**Comment by amirmc** [comment]
Would you mind also updating the page on OCaml.org?

http://ocaml.org/learn/teaching-ocaml.html

**Comment by rizo** [comment]
Alas I lack the time to think how to merge this list with the official docs.

**Comment by amirmc** [comment]
That was actually directed at @Xuefeng-Zhu :)

**Comment by Xuefeng-Zhu** [comment]
Could you please tell me how to update http://ocaml.org/learn/teaching-ocaml.html?

**Comment by rizo** [comment]
Already updated it @Xuefeng-Zhu :)

Here: https://github.com/ocaml/ocaml.org/pull/677

**Comment by rizo** [comment]
@amirmc I know! :) But your comment reminded me of the issue you created some time ago (https://github.com/rizo/awesome-ocaml/issues/35).

**Comment by amirmc** [comment]
Yeah, I think as long as there's up to date info in the places people look then I think we're net-positive :)

@Xuefeng-Zhu, on the top right of each page of OCaml.org is a link that says 'edit this page' (or maybe it's a pencil symbol -- the mobile view has a dropdown). Clicking that takes you directly to the relevant file on GitHub and you can use their WebUI to make an edit and submit a PR.

**Comment by Xuefeng-Zhu** [comment]
Got it. Thanks.

**Pull request merged**
