### PR TITLE
add opam2web

### PR DESCRIPTION
**Pull request by ShalokShalom**

### CODE REVIEW

**Comment by gasche** [comment]
I don't think opam2web fits in this section. Maybe in "packaging"? It could be a remark/footnote in the "opam" line (along with opam-publish and opam2deb?).

**Comment by ShalokShalom** [comment]
A tool to generate a website from an OPAM repository?

**Comment by gasche** [comment]
All the other items in the list in this section are libraries and tools to allow web programming in OCaml (COW, ocamlnet, js_of_ocaml and Bucklescript, Tyxml, ocaml-mustache etc.); `opam2web` is not a generalist web programming tool, it is more a packaging tool -- it displays information about an opam repository in a format that happens to be for the web.

**Comment by Drup** [comment]
I'm not even sure it should be here. It's not a particularly interesting library for ocaml programmers, and it's not even that good.

**Pull request closed without merging**
