### PR TITLE
+digestif

### PR DESCRIPTION
**Pull request by dinosaure**

### CODE REVIEW

**Comment by rizo** [comment]
Thank you for the PR and a nice library! :)

I was wondering if "Algorithms and Data Structures" is the best section to include this. Maybe we should rename "Security" to "Security and Cryptography" and place it there?

What do you think @gasche?

**Comment by gasche** [comment]
I think the change you propose makes sense. Also the description of Digestif could come with a description of some of the hashes supported (SHA variants and Blake2b) -- they seem oriented towards crypto indeed.

**Comment by dinosaure** [comment]
I moved the field in the Security part

**Comment by rizo** [comment]
Thank you and sorry for the delay!

**Pull request merged**
