### PR TITLE
better System stuff (but still partial coverage)

### PR DESCRIPTION
**Pull request by gasche**

### CODE REVIEW

**Comment by gasche** [comment]
Ping?

**Comment by Engil** [comment]
Merged, thank you!

**Comment by rizo** [comment]
@gasche sorry, been busy lately. Added you to the list of contributors of the repo.

**Comment by gasche** [comment]
You're welcome and I didn't mind the wait -- it's just that sometimes I forgot about PR on my own repos. Thanks for the contributor bit, I'll try to keep incrementally improving the document. I hope we can keep it a community-wide effort though, as it is bound to be a bit subjective otherwise.

**Comment by rizo** [comment]
Sure! I agree with you, community contributions are essential. On the other hand people will eventually complain if they find the subjective parts wrong, like when it happened on reddit :smile:

**Comment by gasche** [comment]
@rizo could you clarify what do you had in mind by giving me commit rights? I got email this afternoon about merge requests, and I did what seemed obvious (merge the obvious one, and delay to extract some more information from the innocent contributor in the second case), but I never got an official "pull request merger" around here. I would feel comfortable merging the "obviously fine" stuff, and letting you handle the non-trivial things that require actual decisions (eg. if people want to reorder stuff or whatever), would that work for you?

**Comment by rizo** [comment]
Although this repository is located at my account it is maintained by the community. I keep things open and liberal here, so anyone can contribute. I gave admin access to this project to the most active contributors at the beginning and they've been participating in discussions and helping with pull requests.

So essentially it works like a wiki where things are moderated by volunteers. Every time someone starts actively adding things I just give them write access, as long as the person seems to know what he/she is doing. There're no obligations, help with obvious things is expected, in doubt the things should be discussed first. The idea is to simply build something useful given the availability of everyone involved.

Sorry for not explaining myself and for the lack of information and thank you for your contributions. I probably will add a contribution guide to avoid confusion in the future.

To give you my personal opinion, I thing this project should eventually be added to the official website (and thus be managed by the same governance model). There's already [an open issue](https://github.com/rizo/awesome-ocaml/issues/35) proposing this but I haven't had the time to thing about it properly.

**Pull request closed without merging**
