### PR TITLE
Added MirageOS and OMIcroB to the list

### PR DESCRIPTION
**Pull request by Vertmo**
I added two "specific" compilers to the list !

### CODE REVIEW

**Comment by rizo** [comment]
MirageOS is already present under the [System Programming](https://github.com/rizo/awesome-ocaml#system-programming) section.

I'd gladly accept the OMIcroB addition.

**Comment by gasche** [comment]
Mirage OS is already listed in the System Programming section, which is a better choice I think; could you remove it from the PR?

OMicroB is a nice addition -- I thought that OCaPIC was already listed, but in fact it isn't. While "Compilers" is an ok section to have it in, maybe you could also create a new "Embedded systems" subsection to the "System Programming" section, and also include [the ESP32 backend](https://github.com/sadiqj/ocaml-esp32)?

**Comment by Vertmo** [comment]
Oh sorry, I did not notice it because I was searching for "MirageOS" ^^ I'll correct that right away ! I'll also add OCaPIC and the ESP32 backend as per @gasche suggestion. What are you thought on the new section ?

**Comment by gasche** [comment]
Merged, thanks!

**Comment by rizo** [comment]
Maybe it’s worth having a dedicated “Embedded Development” section? I’m not sure if it strictly classifies as “System Programming”.

@Vertmo thanks!

**Pull request merged**
