### PR TITLE
Added link to the Obandit multi-armed bandit library

### PR DESCRIPTION
**Pull request by freuk**
Added link to the Obandit multi-armed bandit library under the "Science" section.

### CODE REVIEW

**Comment by gasche** [comment]
Nice! I would like to post your library on reddit, but I have to make a choice I don't like:

- either I point to [the homepage](http://freux.fr/oss/obandit.html) and I get the nice picture, but almost no details without following the "Documentation" link
- or I like the [module Obandit](https://freuk.github.io/obandit/api.docdir/Obandit.html) documentation webpage, with serious math formulas and all, but (1) I miss the nice rabbit bandit picture and (2) the link to the "homepage" in the documentation is broken

Can you make this dilemma disappear before I post?

**Comment by freuk** [comment]
Thank you for your interest, and yes, give me a moment. =)

Quoting Gabriel Scherer (2017-11-02 10:58:35)

**Comment by freuk** [comment]
Yep, please point on the documentation webpage:
https://freuk.github.io/obandit/api.docdir/Obandit.html
Thank you for the feedback!
Val

Quoting Valentin Reis (2017-11-02 11:05:52)

**Comment by gasche** [comment]
Done : https://www.reddit.com/r/ocaml/comments/7aamu4/obandit_ocaml_multiarmed_bandits/ .

Minor note: the standard spelling is "OCaml", not "Ocaml".

**Pull request merged**
